# Usage:
#
#   docker build -t bcryptjs-alpine-arm-builder -f Dockerfile-arm .
#   CONTAINER=$(docker create bcryptjs-alpine-arm-builder)
#   # Then copy the artifact to your host:
#   docker cp "$CONTAINER:/usr/local/opt/bcrypt-js/prebuilds" .
#   docker rm "$CONTAINER"

FROM arm64v8/node:16-alpine

ENV project bcrypt-js
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL en_US.UTF-8
ENV LANG ${LC_ALL}

RUN echo "#log: ${project}: Setup system" \
  && set -x \
  && apk add --update build-base python3 \
  && npm i -g prebuildify@5 node-gyp@9 \
  && sync

ADD . /usr/local/opt/${project}
WORKDIR /usr/local/opt/${project}

RUN echo "#log: ${project}: Running build" \
  && set -x \
  && npm ci \
  && npm run build

ARG RUN_TESTS=true

RUN if "${RUN_TESTS}"; then \
    echo "#log ${project}: Running tests" \
    && npm test; \
  else \
    echo "#log ${project}: Tests were skipped!"; \
  fi

CMD /bin/bash -l
